<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ObD3KtRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ObD3KtR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ObD3KtR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attendance' => ['privates', '.errored..service_locator.ObD3KtR.App\\Entity\\Attendances', NULL, 'Cannot autowire service ".service_locator.ObD3KtR": it needs an instance of "App\\Entity\\Attendances" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'attendance' => 'App\\Entity\\Attendances',
            'entityManager' => '?',
        ]);
    }
}
