<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitiesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sc5F6yE.App\Controller\ActivitiesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sc5F6yE.App\\Controller\\ActivitiesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activitiesRepository' => ['privates', 'App\\Repository\\ActivitiesRepository', 'getActivitiesRepositoryService', true],
            'participantRepository' => ['privates', 'App\\Repository\\ActivityParticipantRepository', 'getActivityParticipantRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'activitiesRepository' => 'App\\Repository\\ActivitiesRepository',
            'participantRepository' => 'App\\Repository\\ActivityParticipantRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ActivitiesController::index()', $container);
    }
}
