<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttendances2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vHSzAqf.App\Entity\Attendances' shared service.
     *
     * @return \App\Entity\Attendances
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vHSzAqf": it needs an instance of "App\\Entity\\Attendances" but this type has been excluded in "config/services.yaml".');
    }
}
