<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttendancesControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ObD3KtR.App\Controller\AttendancesController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ObD3KtR'] ?? $container->load('get_ServiceLocator_ObD3KtRService'));

        if (isset($container->privates['.service_locator.ObD3KtR.App\\Controller\\AttendancesController::edit()'])) {
            return $container->privates['.service_locator.ObD3KtR.App\\Controller\\AttendancesController::edit()'];
        }

        return $container->privates['.service_locator.ObD3KtR.App\\Controller\\AttendancesController::edit()'] = $a->withContext('App\\Controller\\AttendancesController::edit()', $container);
    }
}
