<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitiesControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kr6MwHT.App\Controller\ActivitiesController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kr6MwHT.App\\Controller\\ActivitiesController::delete()'] = ($container->privates['.service_locator.kr6MwHT'] ?? $container->load('get_ServiceLocator_Kr6MwHTService'))->withContext('App\\Controller\\ActivitiesController::delete()', $container);
    }
}
