<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityParticipantControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PA3Vb4F.App\Controller\ActivityParticipantController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PA3Vb4F.App\\Controller\\ActivityParticipantController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'participantRepository' => ['privates', 'App\\Repository\\ActivityParticipantRepository', 'getActivityParticipantRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'participantRepository' => 'App\\Repository\\ActivityParticipantRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ActivityParticipantController::index()', $container);
    }
}
