<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttendancesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dcZ32OL.App\Controller\AttendancesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dcZ32OL.App\\Controller\\AttendancesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attendancesRepository' => ['privates', 'App\\Repository\\AttendancesRepository', 'getAttendancesRepositoryService', true],
            'participantRepository' => ['privates', 'App\\Repository\\ActivityParticipantRepository', 'getActivityParticipantRepositoryService', true],
        ], [
            'attendancesRepository' => 'App\\Repository\\AttendancesRepository',
            'participantRepository' => 'App\\Repository\\ActivityParticipantRepository',
        ]))->withContext('App\\Controller\\AttendancesController::index()', $container);
    }
}
