<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseExceptionListenerSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\DatabaseExceptionListenerSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\DatabaseExceptionListenerSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'DatabaseExceptionListenerSubscriber.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['App\\EventSubscriber\\DatabaseExceptionListenerSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\DatabaseExceptionListenerSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\DatabaseExceptionListenerSubscriber'] = new \App\EventSubscriber\DatabaseExceptionListenerSubscriber($a);
    }
}
