<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w6GMCMp.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w6GMCMp.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'activitiesRepository' => ['privates', 'App\\Repository\\ActivitiesRepository', 'getActivitiesRepositoryService', true],
            'fundsRepository' => ['privates', 'App\\Repository\\FundsRepository', 'getFundsRepositoryService', true],
            'proposalsRepository' => ['privates', 'App\\Repository\\ProposalsRepository', 'getProposalsRepositoryService', true],
            'activityParticipantRepository' => ['privates', 'App\\Repository\\ActivityParticipantRepository', 'getActivityParticipantRepositoryService', true],
        ], [
            'usersRepository' => 'App\\Repository\\UsersRepository',
            'activitiesRepository' => 'App\\Repository\\ActivitiesRepository',
            'fundsRepository' => 'App\\Repository\\FundsRepository',
            'proposalsRepository' => 'App\\Repository\\ProposalsRepository',
            'activityParticipantRepository' => 'App\\Repository\\ActivityParticipantRepository',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
