<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFundsControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.saCaDpm.App\Controller\FundsController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.saCaDpm.App\\Controller\\FundsController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fund' => ['privates', '.errored..service_locator.saCaDpm.App\\Entity\\Funds', NULL, 'Cannot autowire service ".service_locator.saCaDpm": it needs an instance of "App\\Entity\\Funds" but this type has been excluded in "config/services.yaml".'],
        ], [
            'fund' => 'App\\Entity\\Funds',
        ]))->withContext('App\\Controller\\FundsController::show()', $container);
    }
}
