<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFundsControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1a8_iWA.App\Controller\FundsController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.1a8_iWA'] ?? $container->load('get_ServiceLocator_1a8IWAService'));

        if (isset($container->privates['.service_locator.1a8_iWA.App\\Controller\\FundsController::edit()'])) {
            return $container->privates['.service_locator.1a8_iWA.App\\Controller\\FundsController::edit()'];
        }

        return $container->privates['.service_locator.1a8_iWA.App\\Controller\\FundsController::edit()'] = $a->withContext('App\\Controller\\FundsController::edit()', $container);
    }
}
