<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProposalsControllerrejectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8O1JMMF.App\Controller\ProposalsController::reject()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8O1JMMF.App\\Controller\\ProposalsController::reject()'] = ($container->privates['.service_locator.8O1JMMF'] ?? $container->load('get_ServiceLocator_8O1JMMFService'))->withContext('App\\Controller\\ProposalsController::reject()', $container);
    }
}
