<?php

namespace ContainerGDJ7EX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllertoggleStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IopeeN_.App\Controller\UsersController::toggleStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IopeeN_.App\\Controller\\UsersController::toggleStatus()'] = ($container->privates['.service_locator.IopeeN_'] ?? $container->load('get_ServiceLocator_IopeeNService'))->withContext('App\\Controller\\UsersController::toggleStatus()', $container);
    }
}
