<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_DEBUG' => '1',
  'DATABASE_URL' => 'mysql://zurmswjm_oris:5twHPJNayZUWfJzc8Ct9@103.97.126.29/zurmswjm_bookclub?serverVersion=8.0.32&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
  'GOOGLE_CLIENT_ID' => '386850841331-ln5r1jntmbukubaqh3g02ggn1r66hs0b.apps.googleusercontent.com',
  'GOOGLE_CLIENT_SECRET' => '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',
  'GOOGLE_REDIRECT_URI' => 'https://127.0.0.1:8000/connect/google/check',
  'APP_SECRET' => '43e3d5b70f5f8f66a07df6ca55c3b3ea',
);
