@startuml
left to right direction
skinparam packageStyle rectangle

actor "Thành viên" as Member
actor "BCN" as BCN
actor "Thủ quỹ" as Treasurer
Treasurer -|> Member

rectangle "Hệ thống quản lý CLB" {
    usecase "Đăng nhập/Đăng xuất" as UC1
    usecase "Xem thông tin cá nhân" as UC2
    usecase "Sửa thông tin cá nhân" as UC3
    usecase "Đăng ký tham gia" as UC4
    usecase "Xem hoạt động" as UC5
    usecase "Điểm danh" as UC6
    usecase "Gửi/chỉnh sửa đề xuất" as UC7
    usecase UC8 as "Quản lý đề xuất
    --
    Xem, duyệt, từ chối"
    
    usecase UC9 as "Quản lý thành viên
    --
    Xem, thêm, sửa,
    xóa, thay đổi vai trò"

    usecase UC11 as "Quản lý hoạt động
    --
    Thêm, sửa, xóa"

    usecase UC12 as "Quản lý quỹ
    --
    Thêm, sửa"


    usecase "Xem thông tin quỹ" as UC13
}

BCN -- UC1
BCN -- UC3
BCN -- UC8
BCN -- UC9
BCN -- UC11
BCN -- UC13

Member - UC1
UC2 -- Member
UC4 -- Member
UC5 -- Member
UC6 -- Member
UC7 -- Member

UC12 -- Treasurer
UC3 ..> UC2 : extend
UC8 <.. UC7 : extend
UC11 <.. UC4 : extend
UC11 <.. UC5 : extend
UC11 <.. UC6 : extend
UC12 <. UC13 : extend
@enduml
