<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1a8IWAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1a8_iWA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1a8_iWA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fund' => ['privates', '.errored..service_locator.1a8_iWA.App\\Entity\\Funds', NULL, 'Cannot autowire service ".service_locator.1a8_iWA": it needs an instance of "App\\Entity\\Funds" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'fund' => 'App\\Entity\\Funds',
            'entityManager' => '?',
        ]);
    }
}
