<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LlULY1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._llULY1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._llULY1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fundsRepository' => ['privates', 'App\\Repository\\FundsRepository', 'getFundsRepositoryService', true],
        ], [
            'fundsRepository' => 'App\\Repository\\FundsRepository',
        ]);
    }
}
