<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitiesControllerjoinActivityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KDXJI49.App\Controller\ActivitiesController::joinActivity()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KDXJI49.App\\Controller\\ActivitiesController::joinActivity()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.KDXJI49.App\\Entity\\Activities', NULL, 'Cannot autowire service ".service_locator.KDXJI49": it needs an instance of "App\\Entity\\Activities" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'participantRepository' => ['privates', 'App\\Repository\\ActivityParticipantRepository', 'getActivityParticipantRepositoryService', true],
        ], [
            'activity' => 'App\\Entity\\Activities',
            'em' => '?',
            'participantRepository' => 'App\\Repository\\ActivityParticipantRepository',
        ]))->withContext('App\\Controller\\ActivitiesController::joinActivity()', $container);
    }
}
