<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitiesControllercancelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kr6MwHT.App\Controller\ActivitiesController::cancel()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.kr6MwHT'] ?? $container->load('get_ServiceLocator_Kr6MwHTService'));

        if (isset($container->privates['.service_locator.kr6MwHT.App\\Controller\\ActivitiesController::cancel()'])) {
            return $container->privates['.service_locator.kr6MwHT.App\\Controller\\ActivitiesController::cancel()'];
        }

        return $container->privates['.service_locator.kr6MwHT.App\\Controller\\ActivitiesController::cancel()'] = $a->withContext('App\\Controller\\ActivitiesController::cancel()', $container);
    }
}
