<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityParticipantControllerjoinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wy0FxXK.App\Controller\ActivityParticipantController::join()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Wy0FxXK'] ?? $container->load('get_ServiceLocator_Wy0FxXKService'));

        if (isset($container->privates['.service_locator.Wy0FxXK.App\\Controller\\ActivityParticipantController::join()'])) {
            return $container->privates['.service_locator.Wy0FxXK.App\\Controller\\ActivityParticipantController::join()'];
        }

        return $container->privates['.service_locator.Wy0FxXK.App\\Controller\\ActivityParticipantController::join()'] = $a->withContext('App\\Controller\\ActivityParticipantController::join()', $container);
    }
}
