<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitiesControllertoggleAttendanceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9KYndu8.App\Controller\ActivitiesController::toggleAttendance()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9KYndu8.App\\Controller\\ActivitiesController::toggleAttendance()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attendancesRepository' => ['privates', 'App\\Repository\\AttendancesRepository', 'getAttendancesRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'attendancesRepository' => 'App\\Repository\\AttendancesRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ActivitiesController::toggleAttendance()', $container);
    }
}
