<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitiesControllerparticipantsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uv8MDlY.App\Controller\ActivitiesController::participants()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Uv8MDlY.App\\Controller\\ActivitiesController::participants()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.Uv8MDlY.App\\Entity\\Activities', NULL, 'Cannot autowire service ".service_locator.Uv8MDlY": it needs an instance of "App\\Entity\\Activities" but this type has been excluded in "config/services.yaml".'],
            'participantRepository' => ['privates', 'App\\Repository\\ActivityParticipantRepository', 'getActivityParticipantRepositoryService', true],
            'attendancesRepository' => ['privates', 'App\\Repository\\AttendancesRepository', 'getAttendancesRepositoryService', true],
        ], [
            'activity' => 'App\\Entity\\Activities',
            'participantRepository' => 'App\\Repository\\ActivityParticipantRepository',
            'attendancesRepository' => 'App\\Repository\\AttendancesRepository',
        ]))->withContext('App\\Controller\\ActivitiesController::participants()', $container);
    }
}
