<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttendancesControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ObD3KtR.App\Controller\AttendancesController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ObD3KtR.App\\Controller\\AttendancesController::delete()'] = ($container->privates['.service_locator.ObD3KtR'] ?? $container->load('get_ServiceLocator_ObD3KtRService'))->withContext('App\\Controller\\AttendancesController::delete()', $container);
    }
}
