<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFundsControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1a8_iWA.App\Controller\FundsController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1a8_iWA.App\\Controller\\FundsController::delete()'] = ($container->privates['.service_locator.1a8_iWA'] ?? $container->load('get_ServiceLocator_1a8IWAService'))->withContext('App\\Controller\\FundsController::delete()', $container);
    }
}
