<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFundsControllerexportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._llULY1.App\Controller\FundsController::export()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._llULY1.App\\Controller\\FundsController::export()'] = ($container->privates['.service_locator._llULY1'] ?? $container->load('get_ServiceLocator_LlULY1Service'))->withContext('App\\Controller\\FundsController::export()', $container);
    }
}
