<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFundsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1a8_iWA.App\Entity\Funds' shared service.
     *
     * @return \App\Entity\Funds
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1a8_iWA": it needs an instance of "App\\Entity\\Funds" but this type has been excluded in "config/services.yaml".');
    }
}
