<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFundsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rPmF_1w.App\Controller\FundsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rPmF_1w.App\\Controller\\FundsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fundsRepository' => ['privates', 'App\\Repository\\FundsRepository', 'getFundsRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'fundsRepository' => 'App\\Repository\\FundsRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\FundsController::index()', $container);
    }
}
