<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerviewSuggestionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nQQV0wW.App\Controller\ProfileController::viewSuggestions()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nQQV0wW.App\\Controller\\ProfileController::viewSuggestions()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ProfileController::viewSuggestions()', $container);
    }
}
