<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProposalsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FmcWgij.App\Controller\ProposalsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FmcWgij.App\\Controller\\ProposalsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'proposalsRepository' => ['privates', 'App\\Repository\\ProposalsRepository', 'getProposalsRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'proposalsRepository' => 'App\\Repository\\ProposalsRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ProposalsController::index()', $container);
    }
}
