<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProposals2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8O1JMMF.App\Entity\Proposals' shared service.
     *
     * @return \App\Entity\Proposals
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8O1JMMF": it needs an instance of "App\\Entity\\Proposals" but this type has been excluded in "config/services.yaml".');
    }
}
