<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllerhistoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DKd2SgE.App\Controller\UsersController::history()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DKd2SgE.App\\Controller\\UsersController::history()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'participantRepository' => ['privates', 'App\\Repository\\ActivityParticipantRepository', 'getActivityParticipantRepositoryService', true],
        ], [
            'participantRepository' => 'App\\Repository\\ActivityParticipantRepository',
        ]))->withContext('App\\Controller\\UsersController::history()', $container);
    }
}
