<?php

namespace ContainerGOvuage;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IopeeN_.App\Controller\UsersController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.IopeeN_'] ?? $container->load('get_ServiceLocator_IopeeNService'));

        if (isset($container->privates['.service_locator.IopeeN_.App\\Controller\\UsersController::show()'])) {
            return $container->privates['.service_locator.IopeeN_.App\\Controller\\UsersController::show()'];
        }

        return $container->privates['.service_locator.IopeeN_.App\\Controller\\UsersController::show()'] = $a->withContext('App\\Controller\\UsersController::show()', $container);
    }
}
