<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Users extends \App\Entity\Users implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'class_id' => [parent::class, 'class_id', null],
        "\0".parent::class."\0".'contact_info' => [parent::class, 'contact_info', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'faculty' => [parent::class, 'faculty', null],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null],
        "\0".parent::class."\0".'googleId' => [parent::class, 'googleId', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'participatedActivities' => [parent::class, 'participatedActivities', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'student_id' => [parent::class, 'student_id', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        'class_id' => [parent::class, 'class_id', null],
        'contact_info' => [parent::class, 'contact_info', null],
        'created_at' => [parent::class, 'created_at', null],
        'email' => [parent::class, 'email', null],
        'faculty' => [parent::class, 'faculty', null],
        'gender' => [parent::class, 'gender', null],
        'googleId' => [parent::class, 'googleId', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'participatedActivities' => [parent::class, 'participatedActivities', null],
        'password' => [parent::class, 'password', null],
        'role' => [parent::class, 'role', null],
        'status' => [parent::class, 'status', null],
        'student_id' => [parent::class, 'student_id', null],
        'updated_at' => [parent::class, 'updated_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
