# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://bookclub/":
    type: upstream
    upstream: "app:http"

"https://bookclub/":
    type: redirect
    to: "https://www.bookclub.io.vn/"