<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8l4i9ME\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8l4i9ME/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8l4i9ME.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8l4i9ME\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8l4i9ME\App_KernelDevDebugContainer([
    'container.build_hash' => '8l4i9ME',
    'container.build_id' => 'fd4bab95',
    'container.build_time' => 1746530522,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8l4i9ME');
