<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGDJ7EX9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGDJ7EX9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGDJ7EX9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGDJ7EX9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGDJ7EX9\App_KernelDevDebugContainer([
    'container.build_hash' => 'GDJ7EX9',
    'container.build_id' => 'aa6cd9da',
    'container.build_time' => 1746515810,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGDJ7EX9');
